changelog:
  categories:
    - title: Breaking Changes
      labels: [breaking-change]
    - title: Features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [bugfix, fix]
    - title: Documentation
      labels: [docs]
    - title: Build & CI
      labels: [build, ci]
    - title: Other Changes
      labels: [chore]

